# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QdwkfxIq3dp7KBF2MJCOntA7NFX7e9ye
"""

m=[203,'hyd',45,True,'Mum',78,175]
m

m[-6]

m[2]

m[2:7]

m[1]

m[0:6]

m[2:-1]

m[0:6:1]

m[2:-2:1]

m[-2:2:-2]

len(m)

m

m.append(72)
m

m.append(10)
m

m.append('Mi')
m

R=[10,45,63,72,93,33,'MI']
R

m.append(597)
m

R.append(597)
print(R)

R.pop(8)
R

R + m

